from .base import *


html_title = 'Films'
cards_label = 'Selected Films'
cards = (
    {'title': 'Earthlings',
     'subtitle': '2005',
     'link': 'https://youtu.be/3XrY2TP0ZyU',
     'preview': '../templates/assets/earthlings.jpg',
     'description': "Narrated by Joaquin Phoenix, writer/director Shaun Monson's 2005 documentary about humanity's economic dependence and treatment of animals is a sobering, hard-hitting reality check into the pet, food, clothing, entertainment, and scientific industries.",
    },
    {'title': 'What the Health',
     'subtitle': '2017',
     'link': 'https://www.youtube.com/watch?v=SN9hIRM3R0A',
     'preview': '../templates/assets/what_the_health.jpg',
     'description': "This documentary film critiques the health impact of meat, fish, eggs and dairy products consumption, and questions the practices of leading health and pharmaceutical organizations. Its primary purpose is to advocate for a plant-based diet.",
    },
    {'title': 'You Are What You Eat: A Twin Experiment',
     'subtitle': '2024',
     'link': 'https://opsociety.org/ops-productions/films/you-are-what-you-eat-a-twin-experiment/',
     'preview': '../templates/assets/twins.jpg',
     'description': 'Identical twins change their diets and lifestyles for eight weeks in a unique scientific experiment designed to explore how certain foods impact the body.',
    },
    {'title': 'Cowspiracy',
     'subtitle': '2014',
     'link': 'https://www.youtube.com/watch?v=UsigH2Skfdg',
     'preview': '../templates/assets/cowspiracy.jpg',
     'description': 'Follow the shocking, yet humorous, journey of an aspiring environmentalist, as he daringly seeks to find the real solution to the most pressing environmental issues and true path to sustainability.',
    },
    {'title': 'Seaspiracy',
     'subtitle': '2021',
     'link': 'https://www.netflix.com/nl-en/title/81014008',
     'preview': '../templates/assets/seaspiracy.jpg',
     'description': 'Passionate about ocean life, a filmmaker sets out to document the harm that humans do to marine species — and uncovers alarming global corruption.',
    },
    {'title': 'Okja',
     'subtitle': '2017',
     'link': 'https://www.netflix.com/nl-en/title/80091936',
     'preview': '../templates/assets/okja.jpg',
     'description': 'A gentle giant and the girl who raised her are caught in the crossfire between animal activism, corporate greed and scientific ethics.',
    },
    {'title': 'The Game Changers',
     'subtitle': '2018',
     'link': 'https://www.youtube.com/watch?v=MIl6aRS452E',
     'preview': '../templates/assets/gamechangers.jpg',
     'description': 'The Game Changers tells the story of James Wilks – elite Special Forces trainer and The Ultimate Fighter winner – as he travels the world on a quest to uncover the optimal diet for human performance. Showcasing elite athletes, special ops soldiers, visionary scientists, cultural icons, and everyday heroes, what James discovers permanently changes his understanding of food and his definition of true strength.',
    },
    {'title': 'Dominion',
     'subtitle': '2018',
     'link': 'https://www.youtube.com/watch?v=LQRAfJyEsko',
     'preview': '../templates/assets/dominion.jpg',
     'description': "Dominion uses drones, hidden and handheld cameras to expose the dark underbelly of modern animal agriculture, questioning the morality and validity of humankind’s dominion over the animal kingdom. While mainly focusing on animals used for food, it also explores other ways animals are exploited and abused by humans, including clothing, entertainment and research.",
    },
    {'title': 'Norm',
     'subtitle': '2017',
     'link': 'https://www.youtube.com/watch?v=poxl0K9UrP0',
     'preview': '../templates/assets/norm.jpg',
     'description': "A short film about two roommates debating over the morality of rape, in a society where raping women is legal and socially accepted.",
    },
    {'title': 'The Most Important Speech You Will Ever Hear',
     'subtitle': '2010',
     'link': 'https://www.youtube.com/watch?v=U5hGQDLprA8',
     'preview': '../templates/assets/most_speech.jpg',
     'description': "An inspirational life-changing speech by Gary Yourofsky at Georgia Tech university, an animal liberation activist, national lecturer on animal rights and veganism, and founder of ADAPTT, a non-profit US organization.",
    },
)
