from .base import *


html_title = 'Zdrowie, przepisy i inne aplikacje'
cards_label = 'Dietetyka, przepisy, lokalizator restauracji, inne'
card_height = 210
cards = (
    {'title': 'Happy Cow',
     'subtitle': 'Aplikacja mobilna i strona internetowa',
     'link': 'https://www.happycow.net',
     'preview': '../templates/assets/happycow.png',
     'description': "Znajdź wegańskie restauracje w pobliżu.",
    },
    {'title': 'Healthy Omnomnom',
     'subtitle': 'Przepisy, Youtube',
     'link': 'https://www.youtube.com/@HealthyOmnomnom',
     'preview': '../templates/assets/omnomnom.jpg',
     'description': "Zobacz, że zdrowe, roślinne jedzenie może być banalne do zrobienia i pysznie smakować!",
    },
    {'title': 'Aleksandra Eulalia Schmidt',
     'subtitle': 'Przepisy, Youtube',
     'link': 'https://www.youtube.com/@AleksandraSchmidt',
     'preview': '../templates/assets/schmidt.jpg',
     'description': "Minimalizm, weganizm, podróże",
    },
    {'title': 'Aśka Rzeźnik',
     'subtitle': 'Przepisy, Instagram',
     'link': 'https://www.instagram.com/askarzeznik/',
     'preview': '../templates/assets/aska.jpg',
     'description': "Jak przejść na weganizm? Porady, proste przepisy, przepisy dla dzieci z alergiami.",
    },
    {'title': 'erVegan',
     'subtitle': 'Przepisy, strona internetowa',
     'link': 'https://ervegan.com/',
     'preview': '../templates/assets/ervegan.jpg',
     'description': "Jego imię to Eryk, a zajmuje się on zawodem dietetyka. Swoją wiedzę z zakresu żywienia zdobywał na Warszawskim Uniwersytecie Medycznym. Na swoim blogu realizuje swoje pasje kulinarne i dietetyczne.",
    },
    {'title': 'Co jedzą polscy weganie',
     'subtitle': 'Grupa, Facebook',
     'link': 'https://www.facebook.com/groups/972104249495759/',
     'preview': '../templates/assets/cojedza.jpg',
     'description': "Zdjęcia wegańskich posiłków domowej roboty, gotowców, fast foodów.",
    },
    {'title': 'Zostań wege na 30 dni!',
     'subtitle': 'Strona internetowa',
     'link': 'https://www.zostanwege.pl/',
     'preview': '../templates/assets/burak.jpg',
     'description': "Chcesz być wege? Nie wiesz jak zacząć? Nie wiesz jak odpowiednio ułożyć swoją dietę? A może wręcz przeciwnie? Lubisz smak mięsa i nie wyobrażasz sobie bez niego posiłku? Dzięki naszej kampanii możesz to zmienić.",
    },
    {'title': 'Iwona Kibil - dietetyk',
     'subtitle': 'Facebook',
     'link': 'https://www.facebook.com/Iwonakibildietetyk/',
     'preview': '../templates/assets/wegecentrum.jpg',
     'description': "Na tym profilu znajdziesz porady na temat bilańsowania dietý roślinnej.",
    },
    {'title': 'Nowości ze sklepów',
     'subtitle': 'Instagram',
     'link': 'https://www.instagram.com/weganskisklad/',
     'preview': '../templates/assets/sklad.jpg',
     'description': "Pokazuję wegańskie produkty.",
    },
    {'title': 'Wegepozytywni',
     'subtitle': 'Instagram',
     'link': 'https://www.instagram.com/wegepozytywni/',
     'preview': '../templates/assets/pozyt.jpg',
     'description': "Wegańskie nowości, testy produktów, wege newsy. Podstawy weganizmu - przepisy i inspiracje.",
    },
    {'title': 'Vegan Workout',
     'subtitle': 'Strona internetowa',
     'link': 'https://veganworkout.org.pl/',
     'preview': '../templates/assets/workout.jpg',
     'description': "Piszemy o diecie roślinnej w sporcie, publikujemy artykuły i tłumaczenia, wywiady ze sportowcami, informacje na temat diety i treningu. Prowadzimy szkolenia z zakresu diety wegańskiej. Organizujemy szkolenia na temat treningu z kettlebells.",
    },
    {'title': 'Vegan Sport',
     'subtitle': 'Strona internetowa',
     'link': 'https://vegansport.pl/',
     'preview': '../templates/assets/vegansport.jpg',
     'description': "Znajdziesz tam profile sportowców wegankich, porady dietetyków i trenerów, a także informacje na temat wegańskiej diety i jej wpływu na zdrowie i wyniki sportowe.",
    },
    {'title': 'Happy Rabbit',
     'subtitle': 'Strona internetowa',
     'link': 'http://www.happyrabbitblog.pl/',
     'preview': '../templates/assets/rabbit.jpg',
     'description': "Kosmetyki wegańskie i nietestowane na zwierzetach.",
    },
    {'title': 'Everyday Hero',
     'subtitle': 'Youtube',
     'link': 'http://www.happyrabbitblog.pl/',
     'preview': '../templates/assets/everyday.jpg',
     'description': "Everyday Hero to kanał o etycznym życiu. Poruszam tutaj kwestie związane z weganizmem, moralnością, ateizmem, filozofią i skuteczną komunikacją.",
    },
    {'title': 'Wegaństwo - podcast',
     'subtitle': 'Youtube',
     'link': 'https://www.youtube.com/@weganstwo_podcast',
     'preview': '../templates/assets/podcast.png',
     'description': "Wraz z zaproszonymi gośćmi wgryzam się w weganizm i rozmawiam o zwierzętach, kuchni, klimacie, ekologii i o kilku innych tematach. Mimo że zwykle patrzę na świat przez zielone okulary, jest to podcast inkluzywny, nie tylko dla wegan i wegetarian. Jeśli zdarza Ci się jeść mięso - tym bardziej zapraszam.",
    },
    {'title': 'Empatia',
     'subtitle': 'Strona internetowa',
     'link': 'https://empatia.pl/',
     'preview': '../templates/assets/empatia.png',
     'description': "Naszą misją jest promowanie idei praw zwierząt i weganizmu, tj. postawy etycznej i stylu życia oznaczających świadome wykluczenie (na tyle, na ile to realne i racjonalne) produktów odzwierzęcych – a zatem minimalizację udziału w eksploatowaniu zwierząt.",
    },
    {'title': 'Juszes',
     'subtitle': 'Youtube',
     'link': 'https://www.youtube.com/user/Juszes',
     'preview': '../templates/assets/juszes.jpg',
     'description': "Testy produktów wegańskich.",
    },
)
