from .base import *


html_title = 'Książki'
cards_label = 'Wybrane książki'
card_height = 450
cards = (
    {'title': 'Dziękuję za świńskie oczy. Jak krzywdzimy zwierzęta',
     'subtitle': 'Dariusz Gzyra, 2018',
     'link': 'https://lubimyczytac.pl/ksiazka/4855194/dziekuje-za-swinskie-oczy-jak-krzywdzimy-zwierzeta',
     'preview': '../templates/assets/swinskie.jpg',
     'description': "Dziękuję za świńskie oczy to ważny głos w debacie na temat naszego stosunku do innych zwierząt. Autor nie tylko pokazuje, że zwierzęta są niezastąpionym źródłem wiedzy o świecie, w tym o ludziach, ale również jak bardzo potrzebna jest prowegańska polityka rozwoju.",
    },
    {'title': 'Polskie mięso, czyli jak zostałem weganinem i przestałem się bać',
     'subtitle': 'Jaś Kapela, 2018',
     'link': 'https://lubimyczytac.pl/ksiazka/4858181/polskie-mieso-czyli-jak-zostalem-weganinem-i-przestalem-sie-bac',
     'preview': '../templates/assets/polskie.jpg',
     'description': "„Polskie mięso” to nie tylko mocny reportaż o zwierzętach, jedzeniu mięsa, weganizmie, ale także poruszająca historia jedzenia - tego jak jedzono, co się je i co będziemy jeść już za kilka lat. Autor w pasjonujący sposób przytacza literaturę, rozmowy z ekspertami, ale i historię znajomych, by nakreślić możliwie jak najszerszy obraz „polskiego mięsa”.",
    },
    {'title': 'Smród, krew i łzy. Włącz myślenie, bądź zmianą',
     'subtitle': 'Sylwia Spurek, 2022',
     'link': 'https://lubimyczytac.pl/ksiazka/5043207/smrod-krew-i-lzy-wlacz-myslenie-badz-zmiana',
     'preview': '../templates/assets/smrod.jpg',
     'description': "System żywnościowy odpowiada za ok. 25–30% światowych emisji gazów cieplarnianych. To odsetek porównywalny z udziałem sektora energetycznego. Dlaczego stare partie polityczne o tym nie mówią? Dlaczego międzynarodowe, europejskie i krajowe strategie działania na rzecz klimatu obchodzą się z tym systemem wyjątkowo łagodnie? To oczywiście zaledwie fragment problemu: przemysł rolny to coś więcej niż tylko źródło zmian klimatycznych. Trudno znaleźć inny element polityki, gospodarki, życia społecznego, który w tak dużym stopniu oddziałuje na nasze życie i ma tak istotny wpływ na naszą przyszłość. Trudno dzisiaj znaleźć ważniejszy problem polityczny.",
    },
    {'title': 'Farba znaczy krewzmianą',
     'subtitle': 'Zenon Kruczyński, 2008',
     'link': 'https://lubimyczytac.pl/ksiazka/4368231/farba-znaczy-krew',
     'preview': '../templates/assets/farba.jpg',
     'description': "Myśliwi to pasjonaci i miłośnicy przyrody. Lasy, łąki i bagna znają jak własną kieszeń. O zwyczajach zwierząt wiedzą wszystko. Potrafią opowiadać o nich godzinami, nie kryjąc zachwytu dla piękna natury. Tak chcą być postrzegani. A jednak nie wystarcza im podglądanie z ukrycia, podziwianie z daleka. Zabijanie zwierząt uzasadniają tradycją, odwiecznym rytuałem. Przed opinią publiczną usprawiedliwiają się koniecznością utrzymania naturalnej równowagi w przyrodzie i ochroną upraw.",
    },
    {'title': 'Peter Singer',
     'subtitle': 'Autor, 18 książek',
     'link': 'https://lubimyczytac.pl/autor/23289/peter-singer#books-and-magazines',
     'preview': '../templates/assets/singer.jpg',
     'description': 'Najbardziej wpływowy, współcześnie żyjący filozof. Obwołany przez amerykański "Times" jednym ze 100 najbardziej wpływowych ludzi na świecie.',
    },
    {'title': 'Aktywizm prozwierzęcy. Instrukcja obsługi',
     'subtitle': 'Katarzyna Biernacka, Joanna Wydrych i inni, 2014',
     'link': 'https://lubimyczytac.pl/ksiazka/253466/aktywizm-prozwierzecy-instrukcja-obslugi',
     'preview': '../templates/assets/aktywizm.jpg',
     'description': "Zbiór artykułów na temat szeroko pojętej aktywności dla zwierząt. Pokazuje różnorodność form i różne podejścia do jej prowadzenia.",
    },
    {'title': 'Wędrówka tusz',
     'subtitle': 'Bartek Sabela, 2023',
     'link': 'https://lubimyczytac.pl/ksiazka/5056580/wedrowka-tusz',
     'preview': '../templates/assets/wedrowka.jpg',
     'description': "Na początku XX wieku pewna gospodyni domowa z hrabstwa Sussex zamówiła pięćdziesiąt kurczaków. W wyniku nieporozumienia przysłano jej pięćset sztuk. Trzy lata później miała ich już dziesięć tysięcy, a hrabstwo stało się największym ośrodkiem produkcji drobiu na świecie. Gdy tematem efektywnego rozmnażania zwierząt zainteresowali się biolodzy, genetycy i chemicy, hodowle szybko zaczęły przypominać masową produkcję.",
    },
)
