from .base import *


html_title = 'Filmy'
cards_label = 'Wybrane filmy'
cards = (
    {'title': 'Mieszkańcy Ziemi',
     'subtitle': '2005',
     'link': 'https://www.youtube.com/watch?v=mmkxGQOmsxU',
     'preview': '../templates/assets/earthlings.jpg',
     'description': "Film dokumentalny Shauna Monsona z 2005 roku, którego narratorem jest Joaquin Phoenix, opowiada o ekonomicznym uzależnieniu ludzkości od zwierząt i ich traktowaniu, jest otrzeźwiającym, mocnym spojrzeniem na przemysł zoologiczny, spożywczy, odzieżowy, rozrywkowy i naukowy.",
    },
    {'title': 'What the Health',
     'subtitle': '2017, Netflix',
     'link': 'https://www.netflix.com/pl/title/80174177',
     'preview': '../templates/assets/what_the_health.jpg',
     'description': "Film opowiada o wpływie diety na zdrowie człowieka i wartych miliardy dolarów branżach medycznej, farmaceutycznej i żywnościowej.",
    },
    {'title': 'Jesteś tym, co jesz: Bliźniaczy eksperyment',
     'subtitle': '2024, Netflix',
     'link': 'https://www.netflix.com/pl/title/81133260',
     'preview': '../templates/assets/twins.jpg',
     'description': 'Bliźnięta jednojajowe przez 8 tygodni stosują różne diety i style życia w ramach eksperymentu badającego wpływ określonych pokarmów na ludzki organizm.',
    },
    {'title': 'Cowspiracy',
     'subtitle': '2014',
     'link': 'https://www.youtube.com/watch?v=18QO0kcN0zU',
     'preview': '../templates/assets/cowspiracy_pl.webp',
     'description': 'Podążaj za szokującą, ale pełną humoru podróżą aspirującego ekologa, który odważnie szuka prawdziwego rozwiązania najbardziej palących problemów środowiskowych i prawdziwej drogi do zrównoważonego rozwoju.',
    },
    {'title': 'Katastrofa na talerzu',
     'subtitle': '2024',
     'link': 'https://youtu.be/WvO1f6eH4Bg',
     'preview': '../templates/assets/natalerzu.jpg',
     'description': 'Trzeci reportaż Green REV Institute to mapa kosztów współczesnej produkcji żywności i mapa rozwiązań dla naszych talerzy. Planeta, zdrowie, aktywizm, nauka, przyszłość kolejnych pokoleń, dzika przyroda, bioróżnorodność...',
    },
    {'title': 'Ciemne strony rybołówstwa',
     'subtitle': '2021, Netflix',
     'link': 'https://www.netflix.com/pl/title/81014008',
     'preview': '../templates/assets/seaspiracy.jpg',
     'description': 'Filmowiec zafascynowany morskim życiem postanawia udokumentować krzywdy, jakie ludzkość wyrządza wodnym stworzeniom — i przy okazji odkrywa patologie branży rybołówczej.',
    },
    {'title': 'Okja',
     'subtitle': '2017, Netflix',
     'link': 'https://www.filmweb.pl/film/Okja-2017-748224',
     'preview': '../templates/assets/okja.jpg',
     'description': 'Młoda dziewczyna ryzykuje życie, chcąc powstrzymać międzynarodową korporację przed schwytaniem jej najlepszego przyjaciela, gigantycznego stworzenia o imieniu Okja. ',
    },
    {'title': 'The Game Changers',
     'subtitle': '2018, napisy',
     'link': 'https://www.youtube.com/watch?v=MIl6aRS452E',
     'preview': '../templates/assets/gamechangers.jpg',
     'description': 'The Game Changers opowiada historię Jamesa Wilksa – elitarnego trenera sił specjalnych i zwycięzcy The Ultimate Fighter – podróżującego po świecie w poszukiwaniu optymalnej diety zapewniającej ludzką wydajność. Prezentując elitarnych sportowców, żołnierzy operacji specjalnych, wizjonerskich naukowców, ikony kultury i bohaterów życia codziennego, to, co odkrywa James, trwale zmienia jego rozumienie jedzenia i definicję prawdziwej siły.',
    },
    {'title': 'Dominion',
     'subtitle': '2018, napisy',
     'link': 'https://www.youtube.com/watch?v=LQRAfJyEsko',
     'preview': '../templates/assets/dominion.jpg',
     'description': "Drony, ukryte i ręczne kamery są wykorzystywane do ujawnienia mrocznego podbrzusza współczesnej hodowli zwierząt, kwestionując moralność panowania ludzkości nad królestwem zwierząt. Skupiając się głównie na zwierzętach wykorzystywanych do produkcji żywności, pokazuje również ich wykorzystanie do produkcji odzieży, rozrywki i badań.",
    },
    {'title': 'Norma',
     'subtitle': '2017, napisy',
     'link': 'https://www.youtube.com/watch?v=poxl0K9UrP0',
     'preview': '../templates/assets/norm.jpg',
     'description': "Krótkometrażowy film o dwóch współlokatorach debatujących nad moralnością gwałtu w społeczeństwie, w którym gwałty na kobietach są legalne i społecznie akceptowane.",
    },
    {'title': 'Najważniejsza przemowa, jaką kiedykolwiek usłyszysz',
     'subtitle': '2010, napisy',
     'link': 'https://www.youtube.com/watch?v=U5hGQDLprA8',
     'preview': '../templates/assets/most_speech.jpg',
     'description': "Inspirujące, zmieniające życie przemówienie Gary'ego Yourofsky'ego na uniwersytecie Georgia Tech, działacza na rzecz wyzwolenia zwierząt, krajowego wykładowcy na temat praw zwierząt i weganizmu oraz założyciela ADAPTT, amerykańskiej organizacji non-profit.",
    },
    {'title': 'Smak Zagłady',
     'subtitle': '2022',
     'link': 'https://youtu.be/_K97B8hTX3w',
     'preview': '../templates/assets/smak_zaglady.jpg',
     'description': "Pełnometrażowy film dokumentalny o prawdziwym problemie, o którym nikt nie chce rozmawiać… Czy będziemy kolejnym gatunkiem na wyginięciu?",
    },
    {'title': '30 dni, 30 wymówek',
     'subtitle': '2022',
     'link': 'https://m.youtube.com/channel/UCqDY6IiyX3MB5zNmVxYBXog',
     'preview': '../templates/assets/30.jpg',
     'description': "Seria filmów o tematyce praw zwierząt, która obala 30 najpopularniejszych wymówek używanych przez ludzi w dyskusjach na temat weganizmu.",
    },
    {'title': 'Casa de Carne',
     'subtitle': '2019, napisy',
     'link': 'https://youtu.be/c1DcFmUrxUQ',
     'preview': '../templates/assets/casade.jpg',
     'description': "Podczas wieczornego wypadu z przyjaciółmi Eric wypróbowuje nową restaurację, która sprawia, że doznania kulinarne zataczają koło. Rozgrywający się w niezbyt odległej, mrocznej przyszłości \"Casa de Carne\" to prowokujący do myślenia film krótkometrażowy o trudnych wyborach i ukrytych prawdach.",
    },
    {'title': 'Nowe śledztwo — te same patologie',
     'subtitle': 'Otwarte Klatki',
     'link': 'https://youtu.be/Er9emouH57k',
     'preview': '../templates/assets/sledztwo.jpg',
     'description': "Bicie, kopanie, ciągnięcie siłą, popędzanie, wykręcanie ogonów, złośliwe zadawanie bólu — tak wygląda rozładunek zwierząt w ubojni Onyśk.",
    },
)
