from .base import *


html_title = 'Фільми'
cards_label = 'Вибрані фільми'
cards = (
    {'title': 'Земляни',
     'subtitle': '2005',
     'link': 'https://www.youtube.com/watch?v=JnphWWm-mTU',
     'preview': '../templates/assets/earthlings.jpg',
     'description': "Документальний фільм 2005 року, озвучений Хоакіном Феніксом, розповідає про економічну залежність людства та поводження з тваринами. Стрічка протвережує і змушує замислитися про індустрію домашніх тварин, кормів, одягу, розваг і науки.",
    },
    {'title': 'Ми є тим, що їмо: Експеримент із близнюками',
     'subtitle': '2024, Netflix',
     'link': 'https://www.themoviedb.org/tv/241849-you-are-what-you-eat-a-twin-experiment?language=uk-UA',
     'preview': '../templates/assets/twins.jpg',
     'description': 'Ідентичні близнюки змінили свій раціон і спосіб життя на вісім тижнів у рамках унікального наукового експерименту, покликаного вивчити, як певні продукти впливають на організм.',
    },
    {'title': "Що таке здоров'я",
     'subtitle': '2017, Netflix',
     'link': 'https://uakino-lu.com/42059-chto-takoe-zdorove.html',
     'preview': '../templates/assets/what_the_health.jpg',
     'description': "Фільм розглядає вплив споживання м'яса, риби, яєць і молочних продуктів на здоров'я людини, а також ставить під сумнів практику провідних медичних і фармацевтичних організацій.",
    },
    {'title': 'Коровозмова',
     'subtitle': '2014',
     'link': 'https://www.youtube.com/watch?v=YK5K5gu_n5I',
     'preview': '../templates/assets/cowspiracy.jpg',
     'description': 'Дивовижна і почасти гумористична подорож еколога-початківця, який сміливо намагається знайти реальне вирішення найгостріших екологічних проблем.',
    },
    {'title': 'Окча',
     'subtitle': '2017, Netflix',
     'link': 'https://uakino.club/filmy/genre-action/14482-okcha.html',
     'preview': '../templates/assets/okja.jpg',
     'description': 'Дівчинка живе на фермі і піклується про одну з еспериментальних гігантських генно-модифікованих свиней, надіслану корпорацією Mirando. Тварину зрештою вилучають і доставляють у Нью-Йорк для забою. Щоб цього не допустити, героїня спільно з "Фронтом звільнення тварин" поспішає їй на допомогу.',
    },
    {'title': 'Переломный момент',
     'subtitle': '2018',
     'link': 'https://uakino-bay.com/10386-perelomnyi-moment.html',
     'preview': '../templates/assets/gamechangers.jpg',
     'description': 'Джеймс Вілкс, елітний тренер спецпризначенців і переможець турніру The Ultimate Fighter, подорожує світом у пошуках оптимальної дієти для підвищення працездатності. Джеймс розмовляє з елітними спортсменами, бійцями спецпризначенців, вченими-провидцями, культурними іконами та повсякденними героями. І те, що він виявляє, назавжди змінює його уявлення про їжу та визначення справжньої сили.',
    },
    {'title': 'Морська змова',
     'subtitle': '2021, Netflix',
     'link': 'https://uakino.club/filmy/documentaries/11920-morska-zmova.html',
     'preview': '../templates/assets/seaspiracy.jpg',
     'description': 'Захоплений життям океану, автор фільму документує шкоду, яку люди завдають морським видам у різних куточках світу, і виявляє глобальну корупцію.',
    },
)
