from .base import *


html_title = 'Рецепты, приложения, другое'
cards_label = 'Рецепты, приложения и другие полезные ресурсы'
card_height = 210
cards = (
    {'title': 'Happy Cow',
     'subtitle': 'Приложение и сайт',
     'link': 'https://www.happycow.net',
     'preview': '../templates/assets/happycow.png',
     'description': "Карта кафе и ресторанов, где есть веге-меню или веге-опции.",
    },
    {'title': 'Веганство в России',
     'subtitle': 'veganrussian.ru',
     'link': 'https://veganrussian.ru/',
     'preview': '../templates/assets/vegrus.jpg',
     'description': "Мы помогаем узнать, какие товары веганские. Для этого мы и наша аудитория проверяем и публикуем их на этом сайте. Это не только продукты питания, но и косметика, бытовая химия, товары для хобби, книги, секс-товары и так далее. Зачастую мы пишем гайды, рассказывая как определить, веганский ли товар.",
    },
    {'title': 'Veggie People',
     'subtitle': 'veggiepeople.org',
     'link': 'https://veggiepeople.org/',
     'preview': '../templates/assets/veggie_people.png',
     'description': "Онлайн-журнал о том, как мир становится веганским. Книги, бренды, маркировки товаров и многое другое.",
    },
    {'title': 'Настя Лисица. Докмед нутрициолог, веган',
     'subtitle': 'Рецепты, Instagram',
     'link': 'https://www.instagram.com/waffledeer/',
     'preview': '../templates/assets/waffle.jpg',
     'description': "Помогаю отказаться от мяса и делаю из людей здоровых веганов с 2018. Без детоксов и страшилок про глютен.",
    },
    {'title': 'Mikhail Vegan',
     'subtitle': 'Рецепты, Youtube',
     'link': 'https://www.youtube.com/@mikhailvegan',
     'preview': '../templates/assets/mikhveg.jpg',
     'description': "Видеоблог с рецептами и новостями о веганстве.",
    },
    {'title': 'Planeat V',
     'subtitle': 'Рецепты, Youtube',
     'link': 'https://www.youtube.com/@planeat-V',
     'preview': '../templates/assets/planeat.jpg',
     'description': "Здесь вы найдете для себя много интересных и вкусных рецептов, которые вы с лёгкостью сможете приготовить у себя дома. Питаться только растительной пищей - это вовсе не скучно и совсем не сложно!",
    },
    {'title': 'Веганские рецепты каждый день',
     'subtitle': 'Рецепты, Instagram',
     'link': 'https://www.instagram.com/veganstvo_syroedenie/',
     'preview': '../templates/assets/vegsyr_inst.jpg',
     'description': "Рецепты вкусных веганских и сыроедческих блюд.",
    },
    {'title': 'Vege.One',
     'subtitle': 'Рецепты',
     'link': 'https://vege.one/',
     'preview': '../templates/assets/vegeone.jpg',
     'description': "Вкусные рецепты веганских, вегетарианских, сыроедческих и постных блюд без мяса.",
    },
)
